apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: jupyterhub
  name: jupyterhub
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: jupyterhub
  template:
    metadata:
      creationTimestamp: ~
      labels:
        run: jupyterhub
    spec:
      containers:
        -
          env:
            -
              name: AUTH0_SUBDOMAIN
              value: dev-u0lrvu8n.auth0.com
            -
              name: OAUTH_CLIENT_ID
              value: oma0otEKBg5MLrEenjZe3BPuB9XPmNgz
            -
              name: OAUTH_CLIENT_SECRET
              value: bjGnkNjpaDibgSKz82YOVrHdWiQdkw90qLFNy0fuh54_97Cu4FWigDc_pCQBvhY5
            -
              name: OAUTH_CALLBACK_URL
              value: "http://a6234a11e82ff4f84afea35a515ab523-727625764.us-west-1.elb.amazonaws.com:8000/hub/login/oauth_callback"
          image: "saurssaurav/jupyterhub-kube-oauth:latest"
          imagePullPolicy: IfNotPresent
          name: jupyterhub
          ports:
            -
              containerPort: 8000
              protocol: TCP
          resources: {}
          terminationMessagePolicy: File
          volumeMounts:
            -
              mountPath: /srv/jupyterhub/jupyterhub_config.py
              name: jupyterhub-config
              subPath: jupyterhub_config.py
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        -
          configMap:
            name: jupyterhub-config
          name: jupyterhub-config
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: jupyterhub
  name: jupyterhub
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: jupyterhub
  type: LoadBalancer