apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-shared
  labels:
    type: gp2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"