---
#install nginx
- name: Remove repository from a specific repo file
  copy:
   src: nginx.repo
   dest: /etc/yum.repos.d

- name: Update repositories cache and install Nginx
  yum:
   name: nginx
   state: present
   update_cache: yes
# Create /etc/nginx/conf.d/ directory
- name: Create nginx directory structure
  file:
   path: /etc/nginx/conf.d/
   state: directory
   mode: 0755
# Deploy kibana.conf with FQDN
- name: Setup Nginx reverse proxy for kibana
  template:
   src: kibana.conf.j2
   dest: /etc/nginx/sites-available
   owner: root
   group: root
   mode: 0644
  register: nginx_needs_restart
# Enable nginx service
- name: Enabling Nginx service
  systemd:
   name: nginx
   enabled: yes
# Start Nginx service
  systemd:
   name: nginx
   state: started
   daemon_reload: yes
# Restart Nginx service
- name: Restart Nginx service
  systemd:
   name: nginx
   state: reloaded
   daemon_reload: yes
