---
#Installing logstash
- name: Adding logstash APT repository
  copy:
   src: logstash.repo
   dest: /etc/yum.repos.d
# Installing Logstash
- name: Update repositories cache and install Logstash
  yum:
   name: logstash
   update_cache: yes
#- name: Configure Beats configuration file
 # template:
  # src=logstash.conf.j2
   #dest=/etc/logstash/conf.d/logstash.conf
   #owner=root
   #group=root
   #mode=0644i
# Start Logstash service
- name: Start Logstash service
  systemd:
   name: logstash
   state: started
   daemon_reload: yes
# Enable Logstash service
- name: Enable Logstash service
  systemd:
   name: logstash
   enabled: yes
